### ISSUE TITLE
Wifi disconnecting randomly

### ISSUE THREAD

**Issue by Alexander-Gerontas** [Havoc-OS/android_frameworks_opt_net_wifi#2]
Hello,

I am expiriencing wifi disconnection issues and I don't know where I should commit my issue. I sent a telegram message to my device maintainer (s8 exynos) and I am awaiting for his respone. Because this could be an issue on other phones too I decided to post it here. My wifi is disconnecting when I am browsing the web, downloading big files for games on play store, torrents, etc. When the phone is locked it will lose wifi connection and I am going to miss all messages from email and facebook mesenger. I also tried installing linege os on my device and it does not have the same issue. On the screenshot that I linked bellow the wificond errors apear once my phone disconnects from wifi. Please fix. 

https://imgur.com/a/7yzJ0ug

**Comment by Sarisan** [comment]
https://github.com/Sarisan/havoc_device_xiaomi_trinket-common/commit/cc3f8de8d65c8b7ebb982be5aba42b2d3f9f4a36
Send to maintainer and let he try this
